### ISSUE TITLE
Option to reload data of dropdowns programmatically

### ISSUE THREAD

**Issue by longinius** [tyme-app/plugins#10]
With the `actionFunction` option it's possible to react to changes of input fields, but it's currently not possible to reload the data passed through a `valueFunction`. This would be useful to load or reload the data for a dropdown after entering i.e. an api key. Something like `formElement.someUniqueID.reload()` to trigger a reload, so the dropdown calls the `valueFunction` again.

The `valueFunctionReloadable` is inconvenient if you have multiple dropdowns that needs to be reloaded, since every dropdown has a separate reload button and the user needs to click all of these.

**Comment by tyme-app** [comment]
Thanks. We'll address that in the next update…

**Comment by tyme-app** [comment]
2024.14 will contain the new option
