### ISSUE TITLE
[Question] Form elements side-by-side?

### ISSUE THREAD

**Issue by isametry** [tyme-app/plugins#4]
If I have some settings narrow enough that they could be placed on one row (e.g. buttons or date pickers), is there a way to do this in my plugin's `form.json`?

Tyme's native exporters (to PDF, CSV etc.) do this with a checkbox and two date fields. Can the same be achieved in a plugin?

<img width="289" alt="Snímek obrazovky 2024-03-12 v 14 28 37" src="https://github.com/tyme-app/plugins/assets/46103746/5bf44bf1-ec12-45ba-9aa1-389695b17584"> 
<img width="302" alt="Snímek obrazovky 2024-03-12 v 14 14 29" src="https://github.com/tyme-app/plugins/assets/46103746/68570d1d-cfdf-4fce-9ef1-f1f9cd04f31c">

(I've tried putting the elements in an array, but that did not work.)

**Comment by lrrrs** [comment]
This is not yet possible, sorry. It's a special date range element. We could make it available via plugins. Thanks.

**Comment by tyme-app** [comment]
The `date_range` type will be available in Tyme 2024.5.

**Comment by tyme-app** [comment]
The update 2024.5 will include the new [daterange](https://github.com/tyme-app/plugins/blob/main/README.md#pluginjson) element.  Expected release: This week.
