### ISSUE TITLE
[Question] Grey out form elements?

### ISSUE THREAD

**Issue by isametry** [tyme-app/plugins#5]
In the plugin settings pane, is there a way to make form elements inactive (greyed out) based on either internal or external logic? 

For example, only have a date picker active and editable if a corresponding checkbox in the form is ticked?

**Comment by tyme-app** [comment]
We’ll add a method you can implement to make changes to any form element, when a value changes. That’s a nice idea, thanks.

**Comment by tyme-app** [comment]
Tyme 2024.5 will have `actionFunctions`, `isHidden` and `isEnabled` properties for all form elements.

**Comment by tyme-app** [comment]
The update 2024.5 will include the [actionFunctions](https://github.com/tyme-app/plugins/blob/main/README.md#plugin-form).  Expected release: This week.
