### ISSUE TITLE
How to read the header of a utils.request?

### ISSUE THREAD

**Issue by isametry** [tyme-app/plugins#6]
I'm writing a Tyme plugin against a service which paginates the data in some of its HTTP responses. Their API is based on REST, which paginates [like this](https://docs.github.com/en/rest/using-the-rest-api/using-pagination-in-the-rest-api). 

Apparently, the response should have a header containing information about the pagination (first and last page etc.). However with the Tyme built-in HTTP helper for plugins, I don't see how I can read these headers. 

The JSON response I get only seems to contain `statusCode` and `result`.

**Comment by isametry** [comment]
#7 is related. To make this style of pagination work, I also need URL parameters after a question mark, which I haven't been able to work out.

**Comment by tyme-app** [comment]
Response headers are currently not exposed to plugins, but we could add them in the next update. Thanks

**Comment by tyme-app** [comment]
The update 2024.5 will include the [headers](https://github.com/tyme-app/plugins/blob/main/guides/scripting_helpers.md#general-calls). Most likely the update will be released this week.
