### ISSUE TITLE
Utils.request is stripping parameters after question mark?

### ISSUE THREAD

**Issue by isametry** [tyme-app/plugins#7]
When calling a HTTP request with `utils.request`, anything after a question mark seems to be ignored from the URL. 

The `'GET'` call I'm performing in my plugin accepts parameters such as `?page=2` or `?query=hello`, but based on my tests, Tyme strips these parameters and only sending the URL up until the question mark? Could this be what's happening?

**Comment by tyme-app** [comment]
Just populate the `parameters` object with your `GET` properties. That's the intended way to send these…
