### ISSUE TITLE
Plugin form is not scrollable and overflows small screens

### ISSUE THREAD

**Issue by longinius** [tyme-app/plugins#9]
The plugin form is not scrollable. With longer forms and smaller screens, the form will overflow and it's no longer possible to reach the import button. 

The screenshot shows a 13" MacBook Pro.

<img width="1440" alt="Screenshot 2024-08-01 at 20 18 45" src="https://github.com/user-attachments/assets/9f06ef9e-0322-4b80-9a0e-9d6d1af2ae2c">

**Comment by tyme-app** [comment]
Thanks. We'll address that in the next update…

**Comment by tyme-app** [comment]
The version 2024.14 will contain the fix.
